name: 'version-control'
description: 'Appleyes semantic versions bases on labels'
author: '4Source'

permissions:
  contents: write
  
# Define your inputs here.
inputs:
  owner: 
    description: 'The owner of the repositry'
    required: true
  repo: 
    description: 'The repository name'
    requiered: true
  pr_number:
    description: 'The number of the pull request'
    requiered: true
  token: 
    description: 'The token to use to access the GitHub API'
    required: true
runs:
  using: node20
  main: dist/index.js
